name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout, set up Yarn and Node.js
        uses: mskelton/setup-yarn
      
      - run: yarn --frozen-lockfile
      - run: yarn lint && yarn build
