name: Publish
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    permissions:
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout, setup Yarn and Node.js
        uses: mskelton/setup-yarn@v1.4.0
      
      - run: yarn --frozen-lockfile
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}